require.config({
	baseUrl:"/",
	paths:{
		"jquery":["http://code.jquery.com/jquery-1.12.4.min","lib/jquery/jquery-1.12.4.min"],
		"cookie":"lib/jquery_plugins/jquery.cookie",
		"fly":"lib/jquery_plugins/jquery.fly.min",
		"template":"lib/arttemplate/template",
		"loadheaderfooter":"js/loadHeaderFooter",
		"bootstrap":"lib/bootstrap/js/bootstrap.min"
	}
})