require.config({
	baseUrl:"/",
	paths:{
		"jquery":["http://code.jquery.com/jquery-1.12.4.min","/mynubia/lib/jquery/jquery-1.12.4.min"],
		"cookie":"/mynubia/lib/jquery_plugins/jquery.cookie",
		"fly":"/mynubia/lib/jquery_plugins/jquery.fly.min",
		"template":"/mynubia/lib/arttemplate/template",
		"loadheaderfooter":"/mynubia/js/loadHeaderFooter",
		"bootstrap":"/mynubia/lib/bootstrap/js/bootstrap.min",
		"elevateZoom":"/mynubia/lib/jquery_plugins/jquery.elevateZoom-3.0.8.min"
	}
})